# Generated by Django 2.1.15 on 2021-01-15 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkNumber', models.IntegerField()),
                ('amount', models.IntegerField(default=0)),
                ('paymentDate', models.DateField()),
                ('details', models.CharField(max_length=200)),
                ('givenOutDate', models.DateField()),
                ('paymentNumberInSeries', models.IntegerField()),
                ('quantityinSeries', models.IntegerField()),
                ('refuseReason', models.CharField(max_length=64)),
                ('refuseDate', models.CharField(max_length=64)),
                ('givenInstead', models.CharField(max_length=200)),
                ('alternativeSupplier', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Supplyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplyerName', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='paymentKind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paymentKind', to='search.PaymentsKind'),
        ),
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='search.Status'),
        ),
        migrations.AddField(
            model_name='payments',
            name='supplyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplyer', to='search.Supplyer'),
        ),
    ]
