# Generated by Django 2.1.15 on 2021-01-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentKind', models.IntegerField()),
                ('checkNumber', models.IntegerField()),
                ('paymentDate', models.DateField()),
                ('supplier', models.CharField(max_length=64)),
                ('details', models.CharField(max_length=200)),
                ('givenOutDate', models.DateField()),
                ('paymentNumberInSeries', models.IntegerField()),
                ('quantityinSeries', models.IntegerField()),
                ('status', models.IntegerField()),
                ('refuseReason', models.CharField(max_length=64)),
                ('refuseDate', models.CharField(max_length=64)),
                ('givenInstead', models.CharField(max_length=200)),
                ('alternativeSupplier', models.CharField(max_length=64)),
            ],
        ),
    ]
