# Generated by Django 2.1.15 on 2021-02-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentskind',
            name='paymentKindCode',
            field=models.IntegerField(unique=True),
        ),
    ]
