# Generated by Django 2.1.15 on 2021-01-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='alternativeSupplier',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='payments',
            name='checkNumber',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='details',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='payments',
            name='givenInstead',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='payments',
            name='givenOutDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paymentNumberInSeries',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='quantityinSeries',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='refuseDate',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='payments',
            name='refuseReason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='search.Status'),
        ),
    ]
