# Generated by Django 2.1.15 on 2021-01-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('definition', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='payments',
            name='paymentKind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paymentsKind', to='search.PaymentsKind'),
        ),
    ]
