# Generated by Django 2.1.15 on 2021-01-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210115_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='search.Status'),
        ),
    ]
