# Generated by Django 2.1.15 on 2021-02-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210212_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentskind',
            name='paymentKindCode',
        ),
        migrations.AlterField(
            model_name='paymentskind',
            name='definition',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
