# Generated by Django 2.1.15 on 2021-01-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210114_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
