# Generated by Django 2.1.15 on 2021-01-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_payments_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentskind',
            name='code',
        ),
    ]
