# Generated by Django 2.1.15 on 2021-01-14 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_remove_paymentskind_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Supplyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplyerName', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='search.Status'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplyer', to='search.Supplyer'),
        ),
    ]
