# Generated by Django 2.1.15 on 2021-02-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210212_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentskind',
            options={},
        ),
    ]
