# Generated by Django 2.1.15 on 2021-01-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210115_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='refuseDate',
            field=models.DateField(blank=True, max_length=64),
        ),
    ]
