# Generated by Django 2.1.15 on 2021-01-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20210114_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='paymentKind',
        ),
        migrations.DeleteModel(
            name='PaymentsKind',
        ),
    ]
