# Generated by Django 2.1.15 on 2021-02-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20210212_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentskind',
            name='paymentKindCode',
            field=models.IntegerField(default=1),
        ),
    ]
