# Generated by Django 2.1.15 on 2021-02-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_paymentskind_paymentkindcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentskind',
            options={'get_latest_by': 'paymentKindCode'},
        ),
    ]
