# Generated by Django 2.1.15 on 2021-01-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20210115_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyer',
            name='supplyerCode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
