# Generated by Django 2.1.15 on 2021-01-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_supplyer_supplyercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentskind',
            name='paymentKindCode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='statusCode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
