# Generated by Django 2.1.15 on 2021-02-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20210212_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentskind',
            name='paymentKindCode',
            field=models.IntegerField(),
        ),
    ]
