# Generated by Django 2.1.15 on 2021-02-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20210212_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentskind',
            name='paymentKindCode',
        ),
    ]
