# Generated by Django 2.1.15 on 2021-02-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_remove_paymentskind_paymentkindcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentskind',
            options={},
        ),
    ]
