# Generated by Django 2.1.15 on 2021-03-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20210212_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='updateDate',
            field=models.DateField(auto_now=True),
        ),
    ]
