# Generated by Django 2.1.15 on 2021-03-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_payments_updatedate'),
        ('search', '0011_payments_updatedate (1)'),
    ]

    operations = [
    ]
