# Generated by Django 2.1.15 on 2021-03-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_merge_20210324_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payments',
            name='checkNumber',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
