# Generated by Django 2.1.15 on 2021-03-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_auto_20210326_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='checkNumber',
            field=models.IntegerField(null=True),
        ),
    ]
